name: IntelliJ Agent - Gradle Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Run Tests
        run: ./gradlew jacocoTestReport

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: gradle-coverage-data.zip
          path: .qodana/code-coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_GRADLE }}
        with:
          args: "--linter,jetbrains/qodana-jvm:latest"
          pr-mode: true
          upload-result: true
