name: IntelliJ Agent - Gradle Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Run Tests
        run: ./gradlew test

      - name: Create coverage-data directory and copy contents
        run: |
          mkdir -p .qodana/code-coverage
          cp -R build/kover/bin-reports/* .qodana/code-coverage/

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: gradle-coverage-data.zip
          path: .qodana/code-coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_GRADLE }}
        with:
          pr-mode: true
          upload-result: true
          use-nightly: true
          args: |
            --property=idea.log.config.file=info.xml
            --baseline,qodana.sarif.json
            --apply-fixes
